server:
  port: 8088
mybatis:
  mapperLocations: classpath:mapper/*.xml
spring:
  profiles:
    active: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    #MySQL配置
    driverClassName: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/s_tiansj_net?characterEncoding=utf8&useUnicode=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    url: jdbc:mysql://localhost:3306/trusteeship?characterEncoding=utf8&useUnicode=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
#    password: b376c4d483edf901
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  redis:
    host: 127.0.0.1 # Redis服务器地址
    port: 6379  # Redis服务器连接端口

super:
  admin: woshiqlf